/*
 * Enum.h
 *
 *  Created on: 28 de nov. de 2015
 *      Author: guidonegri
 */

#ifndef ENUM_H_
#define ENUM_H_

#include <string>

enum CategoriasCrimen { ARSON, ASSAULT, BAD_CHECKS, BRIBERY, BURGLARY, DISORDERLY_CONDUCT, DRIVING_UNDER_INFLUENCE, DRUG_NARCOTIC, DRUNKENNESS, EMBEZZLEMENT, EXTORTION, FAMILY_OFFENSES,
    FORGERY_COUNTERFEITING, FRAUD, GAMBLING, KIDNAPPING, LARCENY_THEFT, LIQUOR_LAWS, LOITERING, MISSING_PERSON, NON_CRIMINAL, OTHER_OFFENSES, PORNOGRAPHY, PROSTITUTION, RECOVERED_VEHICLE,
        ROBBERY, RUNAWAY, SECONDARY_CODES, SEX_OFFENSES_FORCIBLE, SEX_OFFENSES_NON_FORCIBLE, STOLEN_PROPERTY, SUICIDE, SUSPICIOUS_OCC, TREA, TRESPASS, VANDALISM, VEHICLE_THEFT,
            WARRANTS, WEAPON_LAWS };

enum TipoFeature { DISTRICT, DAYWEEK, ANIO, MES, HORA, CUAD };

enum TrainColumns { CATEGORY_TRAIN, DISTRICT_TRAIN, ADDRESS_TRAIN, X_TRAIN, Y_TRAIN, YEAR_TRAIN, MONTH_TRAIN, DAYOFWEEK_TRAIN, DAY_TRAIN, HOUR_TRAIN, MINUTE_TRAIN, XR_TRAIN, YR_TRAIN, CUAD_TRAIN };
enum TestColumns { DISTRICT_TEST, ADDRESS_TEST, X_TEST, Y_TEST, YEAR_TEST, MONTH_TEST, DAYOFWEEK_TEST, DAY_TEST, HOUR_TEST, MINUTE_TEST, XR_TEST, YR_TEST, CUAD_TEST };


#endif /* ENUM_H_ */
