/*
 * Enum.h
 *
 *  Created on: 28 de nov. de 2015
 *      Author: guidonegri
 */

#ifndef ENUM_H_
#define ENUM_H_

#include <string>

enum CategoriasCrimen { ARSON, ASSAULT, BAD_CHECKS, BRIBERY, BURGLARY, DISORDERLY_CONDUCT, DRIVING_UNDER_INFLUENCE, DRUG_NARCOTIC, DRUNKENNESS, EMBEZZLEMENT, EXTORTION, FAMILY_OFFENSES,
    FORGERY_COUNTERFEITING, FRAUD, GAMBLING, KIDNAPPING, LARCENY_THEFT, LIQUOR_LAWS, LOITERING, MISSING_PERSON, NON_CRIMINAL, OTHER_OFFENSES, PORNOGRAPHY, PROSTITUTION, RECOVERED_VEHICLE,
        ROBBERY, RUNAWAY, SECONDARY_CODES, SEX_OFFENSES_FORCIBLE, SEX_OFFENSES_NON_FORCIBLE, STOLEN_PROPERTY, SUICIDE, SUSPICIOUS_OCC, TREA, TRESPASS, VANDALISM, VEHICLE_THEFT,
            WARRANTS, WEAPON_LAWS };

enum TipoFeature { DISTRICT, DAYWEEK, ANIO, MES, HORA, CUAD };

enum TrainColumns { CATEGORY, DISTRICT, ADDRESS, X, Y, YEAR, MONTH, DAYOFWEEK, DAY, HOUR, MINUTE, XR, YR, CUAD };
enum TestColumns { DISTRICT, ADDRESS, X, Y, YEAR, MONTH, DAYOFWEEK, DAY, HOUR, MINUTE, XR, YR, CUAD };


#endif /* ENUM_H_ */
